openapi: 3.0.1
info:
  title: CompReg client
  version: 1.0.0
servers:
- url: /
paths:
  /rest/registry/test:
    get:
      operationId: getTestItem
      responses:
        default:
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/BaseDescription'
          description: default response
      x-accepts:
      - application/xml
  /rest/application.wadl/{path}:
    get:
      operationId: getExternalGrammar
      parameters:
      - explode: false
        in: path
        name: path
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/xml: {}
          description: default response
      x-accepts:
      - application/xml
  /rest/application.wadl:
    get:
      operationId: getWadl
      responses:
        default:
          content:
            application/vnd.sun.wadl+xml: {}
            application/xml: {}
          description: default response
      x-accepts:
      - application/vnd.sun.wadl+xml
      - application/xml
components:
  schemas:
    BaseDescription:
      properties:
        dbId:
          format: int64
          type: integer
        name:
          type: string
        description:
          type: string
        registrationDate:
          format: date-time
          type: string
        creatorName:
          type: string
        dbUserId:
          format: int64
          type: integer
        userId:
          type: string
        domainName:
          type: string
        href:
          type: string
          xml:
            namespace: http://www.w3.org/1999/xlink
        groupName:
          type: string
        status:
          enum:
          - development
          - production
          - deprecated
          type: string
        derivedfrom:
          type: string
        successor:
          type: string
        commentsCount:
          format: int32
          type: integer
        content:
          type: string
        deleted:
          type: boolean
        recommended:
          type: boolean
        public:
          type: boolean
        id:
          type: string
        showInEditor:
          type: boolean
      type: object
      xml:
        name: description

