openapi: 3.0.1
info:
  contact:
    email: cmdi@clarin.eu
    name: CLARIN ERIC
    url: https://www.clarin.eu
  description: Components and profiles registry for the Component Metadata Infrastructure
  title: Component Registry API
  version: "1.0"
servers:
- url: /
paths:
  /rest/registry/items:
    get:
      operationId: getItems
      responses:
        default:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BaseDescription'
                type: array
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/BaseDescription'
                type: array
          description: default response
      x-accepts:
      - application/json
      - application/xml
  /rest/registry/test:
    get:
      operationId: getTestItem
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseDescription'
            application/xml:
              schema:
                $ref: '#/components/schemas/BaseDescription'
          description: default response
      x-accepts:
      - application/json
      - application/xml
  /rest/application.wadl/{path}:
    get:
      operationId: getExternalGrammar
      parameters:
      - explode: false
        in: path
        name: path
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/xml: {}
          description: default response
      x-accepts:
      - application/xml
  /rest/application.wadl:
    get:
      operationId: getWadl
      responses:
        default:
          content:
            application/vnd.sun.wadl+xml: {}
            application/xml: {}
          description: default response
      x-accepts:
      - application/vnd.sun.wadl+xml
      - application/xml
components:
  schemas:
    BaseDescription:
      example:
        successor: successor
        creatorName: creatorName
        description: description
        derivedfrom: derivedfrom
        dbUserId: 6
        userId: userId
        content: content
        recommended: true
        groupName: groupName
        deleted: true
        public: true
        commentsCount: 1
        dbId: 0
        domainName: domainName
        name: name
        registrationDate: 2000-01-23T04:56:07.000+00:00
        isPublic: true
        href: href
        id: id
        showInEditor: true
        status: development
      properties:
        dbId:
          format: int64
          type: integer
        name:
          type: string
        description:
          type: string
        registrationDate:
          format: date-time
          type: string
        creatorName:
          type: string
        dbUserId:
          format: int64
          type: integer
        userId:
          type: string
        domainName:
          type: string
        href:
          type: string
          xml:
            namespace: http://www.w3.org/1999/xlink
        groupName:
          type: string
        status:
          enum:
          - development
          - production
          - deprecated
          type: string
        derivedfrom:
          type: string
        successor:
          type: string
        commentsCount:
          format: int32
          type: integer
        content:
          type: string
        deleted:
          type: boolean
        recommended:
          type: boolean
        public:
          type: boolean
        id:
          type: string
        showInEditor:
          type: boolean
        isPublic:
          type: boolean
      type: object
      xml:
        name: description

