/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.DocumentationType;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ValueSchemeType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.*;
import io.github.threetenjaxb.core.*;

/**
 * Attribute
 */
@JsonPropertyOrder({
  Attribute.JSON_PROPERTY_DOCUMENTATION,
  Attribute.JSON_PROPERTY_ATTRIBUTE_VALUE_SCHEME,
  Attribute.JSON_PROPERTY_AUTO_VALUE,
  Attribute.JSON_PROPERTY_NAME,
  Attribute.JSON_PROPERTY_CONCEPT_LINK,
  Attribute.JSON_PROPERTY_VALUE_SCHEME,
  Attribute.JSON_PROPERTY_REQUIRED,
  Attribute.JSON_PROPERTY_OTHER_ATTRIBUTES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-30T12:42:47.061619+02:00[Europe/Riga]", comments = "Generator version: 7.11.0")
@XmlRootElement(name = "Attribute")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "Attribute")
public class Attribute {
  public static final String JSON_PROPERTY_DOCUMENTATION = "documentation";
  @XmlElement(name = "Documentation")
  @jakarta.annotation.Nullable
  private List<DocumentationType> documentation = new ArrayList<>();

  public static final String JSON_PROPERTY_ATTRIBUTE_VALUE_SCHEME = "attributeValueScheme";
  @XmlElement(name = "ValueScheme")
  @jakarta.annotation.Nullable
  private ValueSchemeType attributeValueScheme;

  public static final String JSON_PROPERTY_AUTO_VALUE = "autoValue";
  @XmlElement(name = "AutoValue")
  @jakarta.annotation.Nullable
  private List<String> autoValue = new ArrayList<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @XmlAttribute(name = "name")
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_CONCEPT_LINK = "conceptLink";
  @XmlAttribute(name = "ConceptLink")
  @jakarta.annotation.Nullable
  private String conceptLink;

  /**
   * Gets or Sets valueScheme
   */
  @XmlType(name="ValueSchemeEnum")
  @XmlEnum(String.class)
  public enum ValueSchemeEnum {
    @XmlEnumValue("BOOLEAN")
    BOOLEAN(String.valueOf("BOOLEAN")),
    
    @XmlEnumValue("DECIMAL")
    DECIMAL(String.valueOf("DECIMAL")),
    
    @XmlEnumValue("FLOAT")
    FLOAT(String.valueOf("FLOAT")),
    
    @XmlEnumValue("INT")
    INT(String.valueOf("INT")),
    
    @XmlEnumValue("STRING")
    STRING(String.valueOf("STRING")),
    
    @XmlEnumValue("ANY_URI")
    ANY_URI(String.valueOf("ANY_URI")),
    
    @XmlEnumValue("DATE")
    DATE(String.valueOf("DATE")),
    
    @XmlEnumValue("G_DAY")
    G_DAY(String.valueOf("G_DAY")),
    
    @XmlEnumValue("G_MONTH")
    G_MONTH(String.valueOf("G_MONTH")),
    
    @XmlEnumValue("G_YEAR")
    G_YEAR(String.valueOf("G_YEAR")),
    
    @XmlEnumValue("TIME")
    TIME(String.valueOf("TIME")),
    
    @XmlEnumValue("DATE_TIME")
    DATE_TIME(String.valueOf("DATE_TIME"));

    private String value;

    ValueSchemeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValueSchemeEnum fromValue(String value) {
      for (ValueSchemeEnum b : ValueSchemeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VALUE_SCHEME = "valueScheme";
  @XmlAttribute(name = "ValueScheme")
  @jakarta.annotation.Nullable
  private ValueSchemeEnum valueScheme;

  public static final String JSON_PROPERTY_REQUIRED = "required";
  @XmlAttribute(name = "Required")
  @jakarta.annotation.Nullable
  private Boolean required;

  public static final String JSON_PROPERTY_OTHER_ATTRIBUTES = "otherAttributes";
  @XmlElement(name = "otherAttributes")
  @jakarta.annotation.Nullable
  private Map<String, String> otherAttributes = new HashMap<>();

  public Attribute() {
  }

  public Attribute documentation(@jakarta.annotation.Nullable List<DocumentationType> documentation) {
    
    this.documentation = documentation;
    return this;
  }

  public Attribute addDocumentationItem(DocumentationType documentationItem) {
    if (this.documentation == null) {
      this.documentation = new ArrayList<>();
    }
    this.documentation.add(documentationItem);
    return this;
  }

  /**
   * Get documentation
   * @return documentation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "Documentation")
  @JacksonXmlElementWrapper(useWrapping = false)

  public List<DocumentationType> getDocumentation() {
    return documentation;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "Documentation")
  @JacksonXmlElementWrapper(useWrapping = false)
  public void setDocumentation(@jakarta.annotation.Nullable List<DocumentationType> documentation) {
    this.documentation = documentation;
  }

  public Attribute attributeValueScheme(@jakarta.annotation.Nullable ValueSchemeType attributeValueScheme) {
    
    this.attributeValueScheme = attributeValueScheme;
    return this;
  }

  /**
   * Get attributeValueScheme
   * @return attributeValueScheme
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ATTRIBUTE_VALUE_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ValueScheme")

  public ValueSchemeType getAttributeValueScheme() {
    return attributeValueScheme;
  }


  @JsonProperty(JSON_PROPERTY_ATTRIBUTE_VALUE_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ValueScheme")
  public void setAttributeValueScheme(@jakarta.annotation.Nullable ValueSchemeType attributeValueScheme) {
    this.attributeValueScheme = attributeValueScheme;
  }

  public Attribute autoValue(@jakarta.annotation.Nullable List<String> autoValue) {
    
    this.autoValue = autoValue;
    return this;
  }

  public Attribute addAutoValueItem(String autoValueItem) {
    if (this.autoValue == null) {
      this.autoValue = new ArrayList<>();
    }
    this.autoValue.add(autoValueItem);
    return this;
  }

  /**
   * Get autoValue
   * @return autoValue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTO_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "AutoValue")
  @JacksonXmlElementWrapper(useWrapping = false)

  public List<String> getAutoValue() {
    return autoValue;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "AutoValue")
  @JacksonXmlElementWrapper(useWrapping = false)
  public void setAutoValue(@jakarta.annotation.Nullable List<String> autoValue) {
    this.autoValue = autoValue;
  }

  public Attribute name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "name", isAttribute = true)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "name", isAttribute = true)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Attribute conceptLink(@jakarta.annotation.Nullable String conceptLink) {
    
    this.conceptLink = conceptLink;
    return this;
  }

  /**
   * Get conceptLink
   * @return conceptLink
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONCEPT_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ConceptLink", isAttribute = true)

  public String getConceptLink() {
    return conceptLink;
  }


  @JsonProperty(JSON_PROPERTY_CONCEPT_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ConceptLink", isAttribute = true)
  public void setConceptLink(@jakarta.annotation.Nullable String conceptLink) {
    this.conceptLink = conceptLink;
  }

  public Attribute valueScheme(@jakarta.annotation.Nullable ValueSchemeEnum valueScheme) {
    
    this.valueScheme = valueScheme;
    return this;
  }

  /**
   * Get valueScheme
   * @return valueScheme
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ValueScheme", isAttribute = true)

  public ValueSchemeEnum getValueScheme() {
    return valueScheme;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ValueScheme", isAttribute = true)
  public void setValueScheme(@jakarta.annotation.Nullable ValueSchemeEnum valueScheme) {
    this.valueScheme = valueScheme;
  }

  public Attribute required(@jakarta.annotation.Nullable Boolean required) {
    
    this.required = required;
    return this;
  }

  /**
   * Get required
   * @return required
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "Required", isAttribute = true)

  public Boolean getRequired() {
    return required;
  }


  @JsonProperty(JSON_PROPERTY_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "Required", isAttribute = true)
  public void setRequired(@jakarta.annotation.Nullable Boolean required) {
    this.required = required;
  }

  public Attribute otherAttributes(@jakarta.annotation.Nullable Map<String, String> otherAttributes) {
    
    this.otherAttributes = otherAttributes;
    return this;
  }

  public Attribute putOtherAttributesItem(String key, String otherAttributesItem) {
    if (this.otherAttributes == null) {
      this.otherAttributes = new HashMap<>();
    }
    this.otherAttributes.put(key, otherAttributesItem);
    return this;
  }

  /**
   * Get otherAttributes
   * @return otherAttributes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTHER_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "otherAttributes")
  @JacksonXmlElementWrapper(useWrapping = false)

  public Map<String, String> getOtherAttributes() {
    return otherAttributes;
  }


  @JsonProperty(JSON_PROPERTY_OTHER_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "otherAttributes")
  @JacksonXmlElementWrapper(useWrapping = false)
  public void setOtherAttributes(@jakarta.annotation.Nullable Map<String, String> otherAttributes) {
    this.otherAttributes = otherAttributes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attribute attribute = (Attribute) o;
    return Objects.equals(this.documentation, attribute.documentation) &&
        Objects.equals(this.attributeValueScheme, attribute.attributeValueScheme) &&
        Objects.equals(this.autoValue, attribute.autoValue) &&
        Objects.equals(this.name, attribute.name) &&
        Objects.equals(this.conceptLink, attribute.conceptLink) &&
        Objects.equals(this.valueScheme, attribute.valueScheme) &&
        Objects.equals(this.required, attribute.required) &&
        Objects.equals(this.otherAttributes, attribute.otherAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentation, attributeValueScheme, autoValue, name, conceptLink, valueScheme, required, otherAttributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Attribute {\n");
    sb.append("    documentation: ").append(toIndentedString(documentation)).append("\n");
    sb.append("    attributeValueScheme: ").append(toIndentedString(attributeValueScheme)).append("\n");
    sb.append("    autoValue: ").append(toIndentedString(autoValue)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    conceptLink: ").append(toIndentedString(conceptLink)).append("\n");
    sb.append("    valueScheme: ").append(toIndentedString(valueScheme)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    otherAttributes: ").append(toIndentedString(otherAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

