/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.AttributeListType;
import eu.clarin.cmdi.componentregistry.openapi.client.model.DocumentationType;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ValueSchemeType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.*;
import io.github.threetenjaxb.core.*;

/**
 * ElementType
 */
@JsonPropertyOrder({
  ElementType.JSON_PROPERTY_DOCUMENTATION,
  ElementType.JSON_PROPERTY_ATTRIBUTE_LIST,
  ElementType.JSON_PROPERTY_VALUE_SCHEME,
  ElementType.JSON_PROPERTY_AUTO_VALUE,
  ElementType.JSON_PROPERTY_NAME,
  ElementType.JSON_PROPERTY_CONCEPT_LINK,
  ElementType.JSON_PROPERTY_CARDINALITY_MIN,
  ElementType.JSON_PROPERTY_CARDINALITY_MAX,
  ElementType.JSON_PROPERTY_MULTILINGUAL,
  ElementType.JSON_PROPERTY_OTHER_ATTRIBUTES,
  ElementType.JSON_PROPERTY_VALUE_SCHEME_ATTRIBUTE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-30T12:42:47.061619+02:00[Europe/Riga]", comments = "Generator version: 7.11.0")
@XmlRootElement(name = "ElementType")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "ElementType")
public class ElementType {
  public static final String JSON_PROPERTY_DOCUMENTATION = "documentation";
  @XmlElement(name = "Documentation")
  @jakarta.annotation.Nullable
  private List<DocumentationType> documentation = new ArrayList<>();

  public static final String JSON_PROPERTY_ATTRIBUTE_LIST = "attributeList";
  @XmlElement(name = "AttributeList")
  @jakarta.annotation.Nullable
  private AttributeListType attributeList;

  public static final String JSON_PROPERTY_VALUE_SCHEME = "valueScheme";
  @XmlElement(name = "ValueScheme")
  @jakarta.annotation.Nullable
  private ValueSchemeType valueScheme;

  public static final String JSON_PROPERTY_AUTO_VALUE = "autoValue";
  @XmlElement(name = "AutoValue")
  @jakarta.annotation.Nullable
  private List<String> autoValue = new ArrayList<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @XmlAttribute(name = "name")
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_CONCEPT_LINK = "conceptLink";
  @XmlAttribute(name = "ConceptLink")
  @jakarta.annotation.Nullable
  private String conceptLink;

  public static final String JSON_PROPERTY_CARDINALITY_MIN = "cardinalityMin";
  @XmlAttribute(name = "CardinalityMin")
  @jakarta.annotation.Nullable
  private List<String> cardinalityMin = new ArrayList<>();

  public static final String JSON_PROPERTY_CARDINALITY_MAX = "cardinalityMax";
  @XmlAttribute(name = "CardinalityMax")
  @jakarta.annotation.Nullable
  private List<String> cardinalityMax = new ArrayList<>();

  public static final String JSON_PROPERTY_MULTILINGUAL = "multilingual";
  @XmlAttribute(name = "Multilingual")
  @jakarta.annotation.Nullable
  private Boolean multilingual;

  public static final String JSON_PROPERTY_OTHER_ATTRIBUTES = "otherAttributes";
  @XmlElement(name = "otherAttributes")
  @jakarta.annotation.Nullable
  private Map<String, String> otherAttributes = new HashMap<>();

  /**
   * Gets or Sets valueSchemeAttribute
   */
  @XmlType(name="ValueSchemeAttributeEnum")
  @XmlEnum(String.class)
  public enum ValueSchemeAttributeEnum {
    @XmlEnumValue("BOOLEAN")
    BOOLEAN(String.valueOf("BOOLEAN")),
    
    @XmlEnumValue("DECIMAL")
    DECIMAL(String.valueOf("DECIMAL")),
    
    @XmlEnumValue("FLOAT")
    FLOAT(String.valueOf("FLOAT")),
    
    @XmlEnumValue("INT")
    INT(String.valueOf("INT")),
    
    @XmlEnumValue("STRING")
    STRING(String.valueOf("STRING")),
    
    @XmlEnumValue("ANY_URI")
    ANY_URI(String.valueOf("ANY_URI")),
    
    @XmlEnumValue("DATE")
    DATE(String.valueOf("DATE")),
    
    @XmlEnumValue("G_DAY")
    G_DAY(String.valueOf("G_DAY")),
    
    @XmlEnumValue("G_MONTH")
    G_MONTH(String.valueOf("G_MONTH")),
    
    @XmlEnumValue("G_YEAR")
    G_YEAR(String.valueOf("G_YEAR")),
    
    @XmlEnumValue("TIME")
    TIME(String.valueOf("TIME")),
    
    @XmlEnumValue("DATE_TIME")
    DATE_TIME(String.valueOf("DATE_TIME"));

    private String value;

    ValueSchemeAttributeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValueSchemeAttributeEnum fromValue(String value) {
      for (ValueSchemeAttributeEnum b : ValueSchemeAttributeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VALUE_SCHEME_ATTRIBUTE = "valueSchemeAttribute";
  @XmlAttribute(name = "ValueScheme")
  @jakarta.annotation.Nullable
  private ValueSchemeAttributeEnum valueSchemeAttribute;

  public ElementType() {
  }

  public ElementType documentation(@jakarta.annotation.Nullable List<DocumentationType> documentation) {
    
    this.documentation = documentation;
    return this;
  }

  public ElementType addDocumentationItem(DocumentationType documentationItem) {
    if (this.documentation == null) {
      this.documentation = new ArrayList<>();
    }
    this.documentation.add(documentationItem);
    return this;
  }

  /**
   * Get documentation
   * @return documentation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "Documentation")
  @JacksonXmlElementWrapper(useWrapping = false)

  public List<DocumentationType> getDocumentation() {
    return documentation;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "Documentation")
  @JacksonXmlElementWrapper(useWrapping = false)
  public void setDocumentation(@jakarta.annotation.Nullable List<DocumentationType> documentation) {
    this.documentation = documentation;
  }

  public ElementType attributeList(@jakarta.annotation.Nullable AttributeListType attributeList) {
    
    this.attributeList = attributeList;
    return this;
  }

  /**
   * Get attributeList
   * @return attributeList
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ATTRIBUTE_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "AttributeList")

  public AttributeListType getAttributeList() {
    return attributeList;
  }


  @JsonProperty(JSON_PROPERTY_ATTRIBUTE_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "AttributeList")
  public void setAttributeList(@jakarta.annotation.Nullable AttributeListType attributeList) {
    this.attributeList = attributeList;
  }

  public ElementType valueScheme(@jakarta.annotation.Nullable ValueSchemeType valueScheme) {
    
    this.valueScheme = valueScheme;
    return this;
  }

  /**
   * Get valueScheme
   * @return valueScheme
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ValueScheme")

  public ValueSchemeType getValueScheme() {
    return valueScheme;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ValueScheme")
  public void setValueScheme(@jakarta.annotation.Nullable ValueSchemeType valueScheme) {
    this.valueScheme = valueScheme;
  }

  public ElementType autoValue(@jakarta.annotation.Nullable List<String> autoValue) {
    
    this.autoValue = autoValue;
    return this;
  }

  public ElementType addAutoValueItem(String autoValueItem) {
    if (this.autoValue == null) {
      this.autoValue = new ArrayList<>();
    }
    this.autoValue.add(autoValueItem);
    return this;
  }

  /**
   * Get autoValue
   * @return autoValue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTO_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "AutoValue")
  @JacksonXmlElementWrapper(useWrapping = false)

  public List<String> getAutoValue() {
    return autoValue;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "AutoValue")
  @JacksonXmlElementWrapper(useWrapping = false)
  public void setAutoValue(@jakarta.annotation.Nullable List<String> autoValue) {
    this.autoValue = autoValue;
  }

  public ElementType name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "name", isAttribute = true)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "name", isAttribute = true)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public ElementType conceptLink(@jakarta.annotation.Nullable String conceptLink) {
    
    this.conceptLink = conceptLink;
    return this;
  }

  /**
   * Get conceptLink
   * @return conceptLink
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONCEPT_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ConceptLink", isAttribute = true)

  public String getConceptLink() {
    return conceptLink;
  }


  @JsonProperty(JSON_PROPERTY_CONCEPT_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ConceptLink", isAttribute = true)
  public void setConceptLink(@jakarta.annotation.Nullable String conceptLink) {
    this.conceptLink = conceptLink;
  }

  public ElementType cardinalityMin(@jakarta.annotation.Nullable List<String> cardinalityMin) {
    
    this.cardinalityMin = cardinalityMin;
    return this;
  }

  public ElementType addCardinalityMinItem(String cardinalityMinItem) {
    if (this.cardinalityMin == null) {
      this.cardinalityMin = new ArrayList<>();
    }
    this.cardinalityMin.add(cardinalityMinItem);
    return this;
  }

  /**
   * Get cardinalityMin
   * @return cardinalityMin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CARDINALITY_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "CardinalityMin", isAttribute = true)
  @JacksonXmlElementWrapper(useWrapping = false)

  public List<String> getCardinalityMin() {
    return cardinalityMin;
  }


  @JsonProperty(JSON_PROPERTY_CARDINALITY_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "CardinalityMin", isAttribute = true)
  @JacksonXmlElementWrapper(useWrapping = false)
  public void setCardinalityMin(@jakarta.annotation.Nullable List<String> cardinalityMin) {
    this.cardinalityMin = cardinalityMin;
  }

  public ElementType cardinalityMax(@jakarta.annotation.Nullable List<String> cardinalityMax) {
    
    this.cardinalityMax = cardinalityMax;
    return this;
  }

  public ElementType addCardinalityMaxItem(String cardinalityMaxItem) {
    if (this.cardinalityMax == null) {
      this.cardinalityMax = new ArrayList<>();
    }
    this.cardinalityMax.add(cardinalityMaxItem);
    return this;
  }

  /**
   * Get cardinalityMax
   * @return cardinalityMax
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CARDINALITY_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "CardinalityMax", isAttribute = true)
  @JacksonXmlElementWrapper(useWrapping = false)

  public List<String> getCardinalityMax() {
    return cardinalityMax;
  }


  @JsonProperty(JSON_PROPERTY_CARDINALITY_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "CardinalityMax", isAttribute = true)
  @JacksonXmlElementWrapper(useWrapping = false)
  public void setCardinalityMax(@jakarta.annotation.Nullable List<String> cardinalityMax) {
    this.cardinalityMax = cardinalityMax;
  }

  public ElementType multilingual(@jakarta.annotation.Nullable Boolean multilingual) {
    
    this.multilingual = multilingual;
    return this;
  }

  /**
   * Get multilingual
   * @return multilingual
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MULTILINGUAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "Multilingual", isAttribute = true)

  public Boolean getMultilingual() {
    return multilingual;
  }


  @JsonProperty(JSON_PROPERTY_MULTILINGUAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "Multilingual", isAttribute = true)
  public void setMultilingual(@jakarta.annotation.Nullable Boolean multilingual) {
    this.multilingual = multilingual;
  }

  public ElementType otherAttributes(@jakarta.annotation.Nullable Map<String, String> otherAttributes) {
    
    this.otherAttributes = otherAttributes;
    return this;
  }

  public ElementType putOtherAttributesItem(String key, String otherAttributesItem) {
    if (this.otherAttributes == null) {
      this.otherAttributes = new HashMap<>();
    }
    this.otherAttributes.put(key, otherAttributesItem);
    return this;
  }

  /**
   * Get otherAttributes
   * @return otherAttributes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTHER_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "otherAttributes")
  @JacksonXmlElementWrapper(useWrapping = false)

  public Map<String, String> getOtherAttributes() {
    return otherAttributes;
  }


  @JsonProperty(JSON_PROPERTY_OTHER_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "otherAttributes")
  @JacksonXmlElementWrapper(useWrapping = false)
  public void setOtherAttributes(@jakarta.annotation.Nullable Map<String, String> otherAttributes) {
    this.otherAttributes = otherAttributes;
  }

  public ElementType valueSchemeAttribute(@jakarta.annotation.Nullable ValueSchemeAttributeEnum valueSchemeAttribute) {
    
    this.valueSchemeAttribute = valueSchemeAttribute;
    return this;
  }

  /**
   * Get valueSchemeAttribute
   * @return valueSchemeAttribute
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_SCHEME_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ValueScheme", isAttribute = true)

  public ValueSchemeAttributeEnum getValueSchemeAttribute() {
    return valueSchemeAttribute;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_SCHEME_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ValueScheme", isAttribute = true)
  public void setValueSchemeAttribute(@jakarta.annotation.Nullable ValueSchemeAttributeEnum valueSchemeAttribute) {
    this.valueSchemeAttribute = valueSchemeAttribute;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElementType elementType = (ElementType) o;
    return Objects.equals(this.documentation, elementType.documentation) &&
        Objects.equals(this.attributeList, elementType.attributeList) &&
        Objects.equals(this.valueScheme, elementType.valueScheme) &&
        Objects.equals(this.autoValue, elementType.autoValue) &&
        Objects.equals(this.name, elementType.name) &&
        Objects.equals(this.conceptLink, elementType.conceptLink) &&
        Objects.equals(this.cardinalityMin, elementType.cardinalityMin) &&
        Objects.equals(this.cardinalityMax, elementType.cardinalityMax) &&
        Objects.equals(this.multilingual, elementType.multilingual) &&
        Objects.equals(this.otherAttributes, elementType.otherAttributes) &&
        Objects.equals(this.valueSchemeAttribute, elementType.valueSchemeAttribute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentation, attributeList, valueScheme, autoValue, name, conceptLink, cardinalityMin, cardinalityMax, multilingual, otherAttributes, valueSchemeAttribute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ElementType {\n");
    sb.append("    documentation: ").append(toIndentedString(documentation)).append("\n");
    sb.append("    attributeList: ").append(toIndentedString(attributeList)).append("\n");
    sb.append("    valueScheme: ").append(toIndentedString(valueScheme)).append("\n");
    sb.append("    autoValue: ").append(toIndentedString(autoValue)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    conceptLink: ").append(toIndentedString(conceptLink)).append("\n");
    sb.append("    cardinalityMin: ").append(toIndentedString(cardinalityMin)).append("\n");
    sb.append("    cardinalityMax: ").append(toIndentedString(cardinalityMax)).append("\n");
    sb.append("    multilingual: ").append(toIndentedString(multilingual)).append("\n");
    sb.append("    otherAttributes: ").append(toIndentedString(otherAttributes)).append("\n");
    sb.append("    valueSchemeAttribute: ").append(toIndentedString(valueSchemeAttribute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

