/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ItemType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.*;
import io.github.threetenjaxb.core.*;

/**
 * EnumerationType
 */
@JsonPropertyOrder({
  EnumerationType.JSON_PROPERTY_APPINFO,
  EnumerationType.JSON_PROPERTY_ITEM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T16:54:28.781907+02:00[Europe/Amsterdam]", comments = "Generator version: 7.8.0")
@XmlRootElement(name = "EnumerationType")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "EnumerationType")
public class EnumerationType {
  public static final String JSON_PROPERTY_APPINFO = "appinfo";
  @XmlElement(name = "appinfo")
  private String appinfo;

  public static final String JSON_PROPERTY_ITEM = "item";
  @XmlElement(name = "item")
  private List<ItemType> item = new ArrayList<>();

  public EnumerationType() {
  }

  public EnumerationType appinfo(String appinfo) {
    
    this.appinfo = appinfo;
    return this;
  }

  /**
   * Get appinfo
   * @return appinfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPINFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "appinfo")

  public String getAppinfo() {
    return appinfo;
  }


  @JsonProperty(JSON_PROPERTY_APPINFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "appinfo")
  public void setAppinfo(String appinfo) {
    this.appinfo = appinfo;
  }

  public EnumerationType item(List<ItemType> item) {
    
    this.item = item;
    return this;
  }

  public EnumerationType addItemItem(ItemType itemItem) {
    if (this.item == null) {
      this.item = new ArrayList<>();
    }
    this.item.add(itemItem);
    return this;
  }

  /**
   * Get item
   * @return item
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "item")
  @JacksonXmlElementWrapper(useWrapping = false)

  public List<ItemType> getItem() {
    return item;
  }


  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "item")
  @JacksonXmlElementWrapper(useWrapping = false)
  public void setItem(List<ItemType> item) {
    this.item = item;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnumerationType enumerationType = (EnumerationType) o;
    return Objects.equals(this.appinfo, enumerationType.appinfo) &&
        Objects.equals(this.item, enumerationType.item);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appinfo, item);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnumerationType {\n");
    sb.append("    appinfo: ").append(toIndentedString(appinfo)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

