/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.*;
import io.github.threetenjaxb.core.*;

/**
 * ProfileDescription
 */
@JsonPropertyOrder({
  ProfileDescription.JSON_PROPERTY_NAME,
  ProfileDescription.JSON_PROPERTY_DESCRIPTION,
  ProfileDescription.JSON_PROPERTY_REGISTRATION_DATE,
  ProfileDescription.JSON_PROPERTY_CREATOR_NAME,
  ProfileDescription.JSON_PROPERTY_USER_ID,
  ProfileDescription.JSON_PROPERTY_DOMAIN_NAME,
  ProfileDescription.JSON_PROPERTY_HREF,
  ProfileDescription.JSON_PROPERTY_GROUP_NAME,
  ProfileDescription.JSON_PROPERTY_STATUS,
  ProfileDescription.JSON_PROPERTY_DERIVEDFROM,
  ProfileDescription.JSON_PROPERTY_SUCCESSOR,
  ProfileDescription.JSON_PROPERTY_COMMENTS_COUNT,
  ProfileDescription.JSON_PROPERTY_RECOMMENDED,
  ProfileDescription.JSON_PROPERTY_SHOW_IN_EDITOR,
  ProfileDescription.JSON_PROPERTY_PUBLIC,
  ProfileDescription.JSON_PROPERTY_ID,
  ProfileDescription.JSON_PROPERTY_IS_PUBLIC
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-30T12:42:47.061619+02:00[Europe/Riga]", comments = "Generator version: 7.11.0")
@XmlRootElement(name = "profileDescription")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "profileDescription")
public class ProfileDescription {
  public static final String JSON_PROPERTY_NAME = "name";
  @XmlElement(name = "name")
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @XmlElement(name = "description")
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_REGISTRATION_DATE = "registrationDate";
  @XmlElement(name = "registrationDate")
  @XmlJavaTypeAdapter(OffsetDateTimeXmlAdapter.class)
  @jakarta.annotation.Nullable
  private OffsetDateTime registrationDate;

  public static final String JSON_PROPERTY_CREATOR_NAME = "creatorName";
  @XmlElement(name = "creatorName")
  @jakarta.annotation.Nullable
  private String creatorName;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @XmlElement(name = "userId")
  @jakarta.annotation.Nullable
  private String userId;

  public static final String JSON_PROPERTY_DOMAIN_NAME = "domainName";
  @XmlElement(name = "domainName")
  @jakarta.annotation.Nullable
  private String domainName;

  public static final String JSON_PROPERTY_HREF = "href";
  @XmlElement(name = "href", namespace = "http://www.w3.org/1999/xlink")
  @jakarta.annotation.Nullable
  private String href;

  public static final String JSON_PROPERTY_GROUP_NAME = "groupName";
  @XmlElement(name = "groupName")
  @jakarta.annotation.Nullable
  private String groupName;

  /**
   * Gets or Sets status
   */
  @XmlType(name="StatusEnum")
  @XmlEnum(String.class)
  public enum StatusEnum {
    @XmlEnumValue("development")
    DEVELOPMENT(String.valueOf("development")),
    
    @XmlEnumValue("production")
    PRODUCTION(String.valueOf("production")),
    
    @XmlEnumValue("deprecated")
    DEPRECATED(String.valueOf("deprecated"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @XmlElement(name = "status")
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_DERIVEDFROM = "derivedfrom";
  @XmlElement(name = "derivedfrom")
  @jakarta.annotation.Nullable
  private String derivedfrom;

  public static final String JSON_PROPERTY_SUCCESSOR = "successor";
  @XmlElement(name = "successor")
  @jakarta.annotation.Nullable
  private String successor;

  public static final String JSON_PROPERTY_COMMENTS_COUNT = "commentsCount";
  @XmlElement(name = "commentsCount")
  @jakarta.annotation.Nullable
  private Integer commentsCount;

  public static final String JSON_PROPERTY_RECOMMENDED = "recommended";
  @XmlElement(name = "recommended")
  @jakarta.annotation.Nullable
  private Boolean recommended;

  public static final String JSON_PROPERTY_SHOW_IN_EDITOR = "showInEditor";
  @XmlElement(name = "showInEditor")
  @jakarta.annotation.Nullable
  private Boolean showInEditor;

  public static final String JSON_PROPERTY_PUBLIC = "public";
  @XmlElement(name = "public")
  @jakarta.annotation.Nullable
  private Boolean _public;

  public static final String JSON_PROPERTY_ID = "id";
  @XmlElement(name = "id")
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_IS_PUBLIC = "isPublic";
  @XmlElement(name = "isPublic")
  @jakarta.annotation.Nullable
  private Boolean isPublic;

  public ProfileDescription() {
  }

  public ProfileDescription name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "name")

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "name")
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public ProfileDescription description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "description")

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "description")
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public ProfileDescription registrationDate(@jakarta.annotation.Nullable OffsetDateTime registrationDate) {
    
    this.registrationDate = registrationDate;
    return this;
  }

  /**
   * Get registrationDate
   * @return registrationDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGISTRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "registrationDate")

  public OffsetDateTime getRegistrationDate() {
    return registrationDate;
  }


  @JsonProperty(JSON_PROPERTY_REGISTRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "registrationDate")
  public void setRegistrationDate(@jakarta.annotation.Nullable OffsetDateTime registrationDate) {
    this.registrationDate = registrationDate;
  }

  public ProfileDescription creatorName(@jakarta.annotation.Nullable String creatorName) {
    
    this.creatorName = creatorName;
    return this;
  }

  /**
   * Get creatorName
   * @return creatorName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATOR_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "creatorName")

  public String getCreatorName() {
    return creatorName;
  }


  @JsonProperty(JSON_PROPERTY_CREATOR_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "creatorName")
  public void setCreatorName(@jakarta.annotation.Nullable String creatorName) {
    this.creatorName = creatorName;
  }

  public ProfileDescription userId(@jakarta.annotation.Nullable String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "userId")

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "userId")
  public void setUserId(@jakarta.annotation.Nullable String userId) {
    this.userId = userId;
  }

  public ProfileDescription domainName(@jakarta.annotation.Nullable String domainName) {
    
    this.domainName = domainName;
    return this;
  }

  /**
   * Get domainName
   * @return domainName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOMAIN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "domainName")

  public String getDomainName() {
    return domainName;
  }


  @JsonProperty(JSON_PROPERTY_DOMAIN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "domainName")
  public void setDomainName(@jakarta.annotation.Nullable String domainName) {
    this.domainName = domainName;
  }

  public ProfileDescription href(@jakarta.annotation.Nullable String href) {
    
    this.href = href;
    return this;
  }

  /**
   * Get href
   * @return href
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "href", namespace = "http://www.w3.org/1999/xlink")

  public String getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "href", namespace = "http://www.w3.org/1999/xlink")
  public void setHref(@jakarta.annotation.Nullable String href) {
    this.href = href;
  }

  public ProfileDescription groupName(@jakarta.annotation.Nullable String groupName) {
    
    this.groupName = groupName;
    return this;
  }

  /**
   * Get groupName
   * @return groupName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "groupName")

  public String getGroupName() {
    return groupName;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "groupName")
  public void setGroupName(@jakarta.annotation.Nullable String groupName) {
    this.groupName = groupName;
  }

  public ProfileDescription status(@jakarta.annotation.Nullable StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "status")

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "status")
  public void setStatus(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
  }

  public ProfileDescription derivedfrom(@jakarta.annotation.Nullable String derivedfrom) {
    
    this.derivedfrom = derivedfrom;
    return this;
  }

  /**
   * Get derivedfrom
   * @return derivedfrom
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DERIVEDFROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "derivedfrom")

  public String getDerivedfrom() {
    return derivedfrom;
  }


  @JsonProperty(JSON_PROPERTY_DERIVEDFROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "derivedfrom")
  public void setDerivedfrom(@jakarta.annotation.Nullable String derivedfrom) {
    this.derivedfrom = derivedfrom;
  }

  public ProfileDescription successor(@jakarta.annotation.Nullable String successor) {
    
    this.successor = successor;
    return this;
  }

  /**
   * Get successor
   * @return successor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUCCESSOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "successor")

  public String getSuccessor() {
    return successor;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESSOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "successor")
  public void setSuccessor(@jakarta.annotation.Nullable String successor) {
    this.successor = successor;
  }

  public ProfileDescription commentsCount(@jakarta.annotation.Nullable Integer commentsCount) {
    
    this.commentsCount = commentsCount;
    return this;
  }

  /**
   * Get commentsCount
   * @return commentsCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "commentsCount")

  public Integer getCommentsCount() {
    return commentsCount;
  }


  @JsonProperty(JSON_PROPERTY_COMMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "commentsCount")
  public void setCommentsCount(@jakarta.annotation.Nullable Integer commentsCount) {
    this.commentsCount = commentsCount;
  }

  public ProfileDescription recommended(@jakarta.annotation.Nullable Boolean recommended) {
    
    this.recommended = recommended;
    return this;
  }

  /**
   * Get recommended
   * @return recommended
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECOMMENDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "recommended")

  public Boolean getRecommended() {
    return recommended;
  }


  @JsonProperty(JSON_PROPERTY_RECOMMENDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "recommended")
  public void setRecommended(@jakarta.annotation.Nullable Boolean recommended) {
    this.recommended = recommended;
  }

  public ProfileDescription showInEditor(@jakarta.annotation.Nullable Boolean showInEditor) {
    
    this.showInEditor = showInEditor;
    return this;
  }

  /**
   * Get showInEditor
   * @return showInEditor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOW_IN_EDITOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "showInEditor")

  public Boolean getShowInEditor() {
    return showInEditor;
  }


  @JsonProperty(JSON_PROPERTY_SHOW_IN_EDITOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "showInEditor")
  public void setShowInEditor(@jakarta.annotation.Nullable Boolean showInEditor) {
    this.showInEditor = showInEditor;
  }

  public ProfileDescription _public(@jakarta.annotation.Nullable Boolean _public) {
    
    this._public = _public;
    return this;
  }

  /**
   * Get _public
   * @return _public
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "public")

  public Boolean getPublic() {
    return _public;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "public")
  public void setPublic(@jakarta.annotation.Nullable Boolean _public) {
    this._public = _public;
  }

  public ProfileDescription id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "id")

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "id")
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public ProfileDescription isPublic(@jakarta.annotation.Nullable Boolean isPublic) {
    
    this.isPublic = isPublic;
    return this;
  }

  /**
   * Get isPublic
   * @return isPublic
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "isPublic")

  public Boolean getIsPublic() {
    return isPublic;
  }


  @JsonProperty(JSON_PROPERTY_IS_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "isPublic")
  public void setIsPublic(@jakarta.annotation.Nullable Boolean isPublic) {
    this.isPublic = isPublic;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileDescription profileDescription = (ProfileDescription) o;
    return Objects.equals(this.name, profileDescription.name) &&
        Objects.equals(this.description, profileDescription.description) &&
        Objects.equals(this.registrationDate, profileDescription.registrationDate) &&
        Objects.equals(this.creatorName, profileDescription.creatorName) &&
        Objects.equals(this.userId, profileDescription.userId) &&
        Objects.equals(this.domainName, profileDescription.domainName) &&
        Objects.equals(this.href, profileDescription.href) &&
        Objects.equals(this.groupName, profileDescription.groupName) &&
        Objects.equals(this.status, profileDescription.status) &&
        Objects.equals(this.derivedfrom, profileDescription.derivedfrom) &&
        Objects.equals(this.successor, profileDescription.successor) &&
        Objects.equals(this.commentsCount, profileDescription.commentsCount) &&
        Objects.equals(this.recommended, profileDescription.recommended) &&
        Objects.equals(this.showInEditor, profileDescription.showInEditor) &&
        Objects.equals(this._public, profileDescription._public) &&
        Objects.equals(this.id, profileDescription.id) &&
        Objects.equals(this.isPublic, profileDescription.isPublic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, registrationDate, creatorName, userId, domainName, href, groupName, status, derivedfrom, successor, commentsCount, recommended, showInEditor, _public, id, isPublic);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileDescription {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    registrationDate: ").append(toIndentedString(registrationDate)).append("\n");
    sb.append("    creatorName: ").append(toIndentedString(creatorName)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    derivedfrom: ").append(toIndentedString(derivedfrom)).append("\n");
    sb.append("    successor: ").append(toIndentedString(successor)).append("\n");
    sb.append("    commentsCount: ").append(toIndentedString(commentsCount)).append("\n");
    sb.append("    recommended: ").append(toIndentedString(recommended)).append("\n");
    sb.append("    showInEditor: ").append(toIndentedString(showInEditor)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

