/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProfileDescription
 */
@JsonPropertyOrder({
  ProfileDescription.JSON_PROPERTY_DB_ID,
  ProfileDescription.JSON_PROPERTY_NAME,
  ProfileDescription.JSON_PROPERTY_DESCRIPTION,
  ProfileDescription.JSON_PROPERTY_REGISTRATION_DATE,
  ProfileDescription.JSON_PROPERTY_CREATOR_NAME,
  ProfileDescription.JSON_PROPERTY_DB_USER_ID,
  ProfileDescription.JSON_PROPERTY_USER_ID,
  ProfileDescription.JSON_PROPERTY_DOMAIN_NAME,
  ProfileDescription.JSON_PROPERTY_HREF,
  ProfileDescription.JSON_PROPERTY_GROUP_NAME,
  ProfileDescription.JSON_PROPERTY_STATUS,
  ProfileDescription.JSON_PROPERTY_DERIVEDFROM,
  ProfileDescription.JSON_PROPERTY_SUCCESSOR,
  ProfileDescription.JSON_PROPERTY_COMMENTS_COUNT,
  ProfileDescription.JSON_PROPERTY_CONTENT,
  ProfileDescription.JSON_PROPERTY_DELETED,
  ProfileDescription.JSON_PROPERTY_RECOMMENDED,
  ProfileDescription.JSON_PROPERTY_SHOW_IN_EDITOR,
  ProfileDescription.JSON_PROPERTY_PUBLIC,
  ProfileDescription.JSON_PROPERTY_ID,
  ProfileDescription.JSON_PROPERTY_TYPE,
  ProfileDescription.JSON_PROPERTY_PROFILE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-17T13:10:36.372458+03:00[Europe/Riga]", comments = "Generator version: 7.8.0")
public class ProfileDescription {
  public static final String JSON_PROPERTY_DB_ID = "dbId";
  private Long dbId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_REGISTRATION_DATE = "registrationDate";
  private OffsetDateTime registrationDate;

  public static final String JSON_PROPERTY_CREATOR_NAME = "creatorName";
  private String creatorName;

  public static final String JSON_PROPERTY_DB_USER_ID = "dbUserId";
  private Long dbUserId;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private String userId;

  public static final String JSON_PROPERTY_DOMAIN_NAME = "domainName";
  private String domainName;

  public static final String JSON_PROPERTY_HREF = "href";
  private String href;

  public static final String JSON_PROPERTY_GROUP_NAME = "groupName";
  private String groupName;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    DEVELOPMENT("DEVELOPMENT"),
    
    PRODUCTION("PRODUCTION"),
    
    DEPRECATED("DEPRECATED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_DERIVEDFROM = "derivedfrom";
  private String derivedfrom;

  public static final String JSON_PROPERTY_SUCCESSOR = "successor";
  private String successor;

  public static final String JSON_PROPERTY_COMMENTS_COUNT = "commentsCount";
  private Integer commentsCount;

  public static final String JSON_PROPERTY_CONTENT = "content";
  private String content;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public static final String JSON_PROPERTY_RECOMMENDED = "recommended";
  private Boolean recommended;

  public static final String JSON_PROPERTY_SHOW_IN_EDITOR = "showInEditor";
  private Boolean showInEditor;

  public static final String JSON_PROPERTY_PUBLIC = "public";
  private Boolean _public;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_PROFILE = "profile";
  private Boolean profile;

  public ProfileDescription() {
  }

  public ProfileDescription dbId(Long dbId) {
    
    this.dbId = dbId;
    return this;
  }

  /**
   * Get dbId
   * @return dbId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDbId() {
    return dbId;
  }


  @JsonProperty(JSON_PROPERTY_DB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDbId(Long dbId) {
    this.dbId = dbId;
  }

  public ProfileDescription name(String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  public ProfileDescription description(String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }

  public ProfileDescription registrationDate(OffsetDateTime registrationDate) {
    
    this.registrationDate = registrationDate;
    return this;
  }

  /**
   * Get registrationDate
   * @return registrationDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGISTRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRegistrationDate() {
    return registrationDate;
  }


  @JsonProperty(JSON_PROPERTY_REGISTRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegistrationDate(OffsetDateTime registrationDate) {
    this.registrationDate = registrationDate;
  }

  public ProfileDescription creatorName(String creatorName) {
    
    this.creatorName = creatorName;
    return this;
  }

  /**
   * Get creatorName
   * @return creatorName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATOR_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatorName() {
    return creatorName;
  }


  @JsonProperty(JSON_PROPERTY_CREATOR_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatorName(String creatorName) {
    this.creatorName = creatorName;
  }

  public ProfileDescription dbUserId(Long dbUserId) {
    
    this.dbUserId = dbUserId;
    return this;
  }

  /**
   * Get dbUserId
   * @return dbUserId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DB_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDbUserId() {
    return dbUserId;
  }


  @JsonProperty(JSON_PROPERTY_DB_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDbUserId(Long dbUserId) {
    this.dbUserId = dbUserId;
  }

  public ProfileDescription userId(String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(String userId) {
    this.userId = userId;
  }

  public ProfileDescription domainName(String domainName) {
    
    this.domainName = domainName;
    return this;
  }

  /**
   * Get domainName
   * @return domainName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOMAIN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDomainName() {
    return domainName;
  }


  @JsonProperty(JSON_PROPERTY_DOMAIN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomainName(String domainName) {
    this.domainName = domainName;
  }

  public ProfileDescription href(String href) {
    
    this.href = href;
    return this;
  }

  /**
   * Get href
   * @return href
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHref(String href) {
    this.href = href;
  }

  public ProfileDescription groupName(String groupName) {
    
    this.groupName = groupName;
    return this;
  }

  /**
   * Get groupName
   * @return groupName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupName() {
    return groupName;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public ProfileDescription status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ProfileDescription derivedfrom(String derivedfrom) {
    
    this.derivedfrom = derivedfrom;
    return this;
  }

  /**
   * Get derivedfrom
   * @return derivedfrom
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DERIVEDFROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDerivedfrom() {
    return derivedfrom;
  }


  @JsonProperty(JSON_PROPERTY_DERIVEDFROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDerivedfrom(String derivedfrom) {
    this.derivedfrom = derivedfrom;
  }

  public ProfileDescription successor(String successor) {
    
    this.successor = successor;
    return this;
  }

  /**
   * Get successor
   * @return successor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUCCESSOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSuccessor() {
    return successor;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESSOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccessor(String successor) {
    this.successor = successor;
  }

  public ProfileDescription commentsCount(Integer commentsCount) {
    
    this.commentsCount = commentsCount;
    return this;
  }

  /**
   * Get commentsCount
   * @return commentsCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCommentsCount() {
    return commentsCount;
  }


  @JsonProperty(JSON_PROPERTY_COMMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommentsCount(Integer commentsCount) {
    this.commentsCount = commentsCount;
  }

  public ProfileDescription content(String content) {
    
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContent() {
    return content;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(String content) {
    this.content = content;
  }

  public ProfileDescription deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

  /**
   * Get deleted
   * @return deleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public ProfileDescription recommended(Boolean recommended) {
    
    this.recommended = recommended;
    return this;
  }

  /**
   * Get recommended
   * @return recommended
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECOMMENDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRecommended() {
    return recommended;
  }


  @JsonProperty(JSON_PROPERTY_RECOMMENDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecommended(Boolean recommended) {
    this.recommended = recommended;
  }

  public ProfileDescription showInEditor(Boolean showInEditor) {
    
    this.showInEditor = showInEditor;
    return this;
  }

  /**
   * Get showInEditor
   * @return showInEditor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOW_IN_EDITOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShowInEditor() {
    return showInEditor;
  }


  @JsonProperty(JSON_PROPERTY_SHOW_IN_EDITOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowInEditor(Boolean showInEditor) {
    this.showInEditor = showInEditor;
  }

  public ProfileDescription _public(Boolean _public) {
    
    this._public = _public;
    return this;
  }

  /**
   * Get _public
   * @return _public
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPublic() {
    return _public;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublic(Boolean _public) {
    this._public = _public;
  }

  public ProfileDescription id(String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }

  public ProfileDescription type(String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }

  public ProfileDescription profile(Boolean profile) {
    
    this.profile = profile;
    return this;
  }

  /**
   * Get profile
   * @return profile
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getProfile() {
    return profile;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfile(Boolean profile) {
    this.profile = profile;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileDescription profileDescription = (ProfileDescription) o;
    return Objects.equals(this.dbId, profileDescription.dbId) &&
        Objects.equals(this.name, profileDescription.name) &&
        Objects.equals(this.description, profileDescription.description) &&
        Objects.equals(this.registrationDate, profileDescription.registrationDate) &&
        Objects.equals(this.creatorName, profileDescription.creatorName) &&
        Objects.equals(this.dbUserId, profileDescription.dbUserId) &&
        Objects.equals(this.userId, profileDescription.userId) &&
        Objects.equals(this.domainName, profileDescription.domainName) &&
        Objects.equals(this.href, profileDescription.href) &&
        Objects.equals(this.groupName, profileDescription.groupName) &&
        Objects.equals(this.status, profileDescription.status) &&
        Objects.equals(this.derivedfrom, profileDescription.derivedfrom) &&
        Objects.equals(this.successor, profileDescription.successor) &&
        Objects.equals(this.commentsCount, profileDescription.commentsCount) &&
        Objects.equals(this.content, profileDescription.content) &&
        Objects.equals(this.deleted, profileDescription.deleted) &&
        Objects.equals(this.recommended, profileDescription.recommended) &&
        Objects.equals(this.showInEditor, profileDescription.showInEditor) &&
        Objects.equals(this._public, profileDescription._public) &&
        Objects.equals(this.id, profileDescription.id) &&
        Objects.equals(this.type, profileDescription.type) &&
        Objects.equals(this.profile, profileDescription.profile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dbId, name, description, registrationDate, creatorName, dbUserId, userId, domainName, href, groupName, status, derivedfrom, successor, commentsCount, content, deleted, recommended, showInEditor, _public, id, type, profile);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileDescription {\n");
    sb.append("    dbId: ").append(toIndentedString(dbId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    registrationDate: ").append(toIndentedString(registrationDate)).append("\n");
    sb.append("    creatorName: ").append(toIndentedString(creatorName)).append("\n");
    sb.append("    dbUserId: ").append(toIndentedString(dbUserId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    derivedfrom: ").append(toIndentedString(derivedfrom)).append("\n");
    sb.append("    successor: ").append(toIndentedString(successor)).append("\n");
    sb.append("    commentsCount: ").append(toIndentedString(commentsCount)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    recommended: ").append(toIndentedString(recommended)).append("\n");
    sb.append("    showInEditor: ").append(toIndentedString(showInEditor)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

