/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ProfileDescription;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProfileDescriptionsObject
 */
@JsonPropertyOrder({
  ProfileDescriptionsObject.JSON_PROPERTY_PROFILE_DESCRIPTIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-17T13:10:36.372458+03:00[Europe/Riga]", comments = "Generator version: 7.8.0")
public class ProfileDescriptionsObject {
  public static final String JSON_PROPERTY_PROFILE_DESCRIPTIONS = "profileDescriptions";
  private List<ProfileDescription> profileDescriptions = new ArrayList<>();

  public ProfileDescriptionsObject() {
  }

  public ProfileDescriptionsObject profileDescriptions(List<ProfileDescription> profileDescriptions) {
    
    this.profileDescriptions = profileDescriptions;
    return this;
  }

  public ProfileDescriptionsObject addProfileDescriptionsItem(ProfileDescription profileDescriptionsItem) {
    if (this.profileDescriptions == null) {
      this.profileDescriptions = new ArrayList<>();
    }
    this.profileDescriptions.add(profileDescriptionsItem);
    return this;
  }

  /**
   * Get profileDescriptions
   * @return profileDescriptions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE_DESCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProfileDescription> getProfileDescriptions() {
    return profileDescriptions;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE_DESCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfileDescriptions(List<ProfileDescription> profileDescriptions) {
    this.profileDescriptions = profileDescriptions;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileDescriptionsObject profileDescriptionsObject = (ProfileDescriptionsObject) o;
    return Objects.equals(this.profileDescriptions, profileDescriptionsObject.profileDescriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileDescriptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileDescriptionsObject {\n");
    sb.append("    profileDescriptions: ").append(toIndentedString(profileDescriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

