/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.RssChannel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Rss
 */
@JsonPropertyOrder({
  Rss.JSON_PROPERTY_CHANNEL,
  Rss.JSON_PROPERTY_ANY,
  Rss.JSON_PROPERTY_VERSION,
  Rss.JSON_PROPERTY_OTHER_ATTRIBUTES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-17T13:10:36.372458+03:00[Europe/Riga]", comments = "Generator version: 7.8.0")
public class Rss {
  public static final String JSON_PROPERTY_CHANNEL = "channel";
  private RssChannel channel;

  public static final String JSON_PROPERTY_ANY = "any";
  private List<Object> any = new ArrayList<>();

  public static final String JSON_PROPERTY_VERSION = "version";
  private Double version;

  public static final String JSON_PROPERTY_OTHER_ATTRIBUTES = "otherAttributes";
  private Map<String, String> otherAttributes = new HashMap<>();

  public Rss() {
  }

  public Rss channel(RssChannel channel) {
    
    this.channel = channel;
    return this;
  }

  /**
   * Get channel
   * @return channel
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHANNEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RssChannel getChannel() {
    return channel;
  }


  @JsonProperty(JSON_PROPERTY_CHANNEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChannel(RssChannel channel) {
    this.channel = channel;
  }

  public Rss any(List<Object> any) {
    
    this.any = any;
    return this;
  }

  public Rss addAnyItem(Object anyItem) {
    if (this.any == null) {
      this.any = new ArrayList<>();
    }
    this.any.add(anyItem);
    return this;
  }

  /**
   * Get any
   * @return any
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getAny() {
    return any;
  }


  @JsonProperty(JSON_PROPERTY_ANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAny(List<Object> any) {
    this.any = any;
  }

  public Rss version(Double version) {
    
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(Double version) {
    this.version = version;
  }

  public Rss otherAttributes(Map<String, String> otherAttributes) {
    
    this.otherAttributes = otherAttributes;
    return this;
  }

  public Rss putOtherAttributesItem(String key, String otherAttributesItem) {
    if (this.otherAttributes == null) {
      this.otherAttributes = new HashMap<>();
    }
    this.otherAttributes.put(key, otherAttributesItem);
    return this;
  }

  /**
   * Get otherAttributes
   * @return otherAttributes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTHER_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getOtherAttributes() {
    return otherAttributes;
  }


  @JsonProperty(JSON_PROPERTY_OTHER_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtherAttributes(Map<String, String> otherAttributes) {
    this.otherAttributes = otherAttributes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rss rss = (Rss) o;
    return Objects.equals(this.channel, rss.channel) &&
        Objects.equals(this.any, rss.any) &&
        Objects.equals(this.version, rss.version) &&
        Objects.equals(this.otherAttributes, rss.otherAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, any, version, otherAttributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rss {\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    any: ").append(toIndentedString(any)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    otherAttributes: ").append(toIndentedString(otherAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

