/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.Category;
import eu.clarin.cmdi.componentregistry.openapi.client.model.Cloud;
import eu.clarin.cmdi.componentregistry.openapi.client.model.Image;
import eu.clarin.cmdi.componentregistry.openapi.client.model.RssItem;
import eu.clarin.cmdi.componentregistry.openapi.client.model.SkipDaysList;
import eu.clarin.cmdi.componentregistry.openapi.client.model.SkipHoursList;
import eu.clarin.cmdi.componentregistry.openapi.client.model.TextInput;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RssChannel
 */
@JsonPropertyOrder({
  RssChannel.JSON_PROPERTY_TITLE,
  RssChannel.JSON_PROPERTY_LINK,
  RssChannel.JSON_PROPERTY_DESCRIPTION,
  RssChannel.JSON_PROPERTY_LANGUAGE,
  RssChannel.JSON_PROPERTY_COPYRIGHT,
  RssChannel.JSON_PROPERTY_MANAGING_EDITOR,
  RssChannel.JSON_PROPERTY_WEB_MASTER,
  RssChannel.JSON_PROPERTY_PUB_DATE,
  RssChannel.JSON_PROPERTY_LAST_BUILD_DATE,
  RssChannel.JSON_PROPERTY_CATEGORY,
  RssChannel.JSON_PROPERTY_GENERATOR,
  RssChannel.JSON_PROPERTY_DOCS,
  RssChannel.JSON_PROPERTY_CLOUD,
  RssChannel.JSON_PROPERTY_TTL,
  RssChannel.JSON_PROPERTY_IMAGE,
  RssChannel.JSON_PROPERTY_RATING,
  RssChannel.JSON_PROPERTY_TEXT_INPUT,
  RssChannel.JSON_PROPERTY_SKIP_HOURS,
  RssChannel.JSON_PROPERTY_SKIP_DAYS,
  RssChannel.JSON_PROPERTY_ITEM,
  RssChannel.JSON_PROPERTY_OTHER_ATTRIBUTES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-17T13:10:36.372458+03:00[Europe/Riga]", comments = "Generator version: 7.8.0")
public class RssChannel {
  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_LINK = "link";
  private String link;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_COPYRIGHT = "copyright";
  private String copyright;

  public static final String JSON_PROPERTY_MANAGING_EDITOR = "managingEditor";
  private String managingEditor;

  public static final String JSON_PROPERTY_WEB_MASTER = "webMaster";
  private String webMaster;

  public static final String JSON_PROPERTY_PUB_DATE = "pubDate";
  private String pubDate;

  public static final String JSON_PROPERTY_LAST_BUILD_DATE = "lastBuildDate";
  private String lastBuildDate;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  private Category category;

  public static final String JSON_PROPERTY_GENERATOR = "generator";
  private String generator;

  public static final String JSON_PROPERTY_DOCS = "docs";
  private String docs;

  public static final String JSON_PROPERTY_CLOUD = "cloud";
  private Cloud cloud;

  public static final String JSON_PROPERTY_TTL = "ttl";
  private Integer ttl;

  public static final String JSON_PROPERTY_IMAGE = "image";
  private Image image;

  public static final String JSON_PROPERTY_RATING = "rating";
  private String rating;

  public static final String JSON_PROPERTY_TEXT_INPUT = "textInput";
  private TextInput textInput;

  public static final String JSON_PROPERTY_SKIP_HOURS = "skipHours";
  private SkipHoursList skipHours;

  public static final String JSON_PROPERTY_SKIP_DAYS = "skipDays";
  private SkipDaysList skipDays;

  public static final String JSON_PROPERTY_ITEM = "item";
  private List<RssItem> item = new ArrayList<>();

  public static final String JSON_PROPERTY_OTHER_ATTRIBUTES = "otherAttributes";
  private Map<String, String> otherAttributes = new HashMap<>();

  public RssChannel() {
  }

  public RssChannel title(String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTitle(String title) {
    this.title = title;
  }

  public RssChannel link(String link) {
    
    this.link = link;
    return this;
  }

  /**
   * Get link
   * @return link
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLink(String link) {
    this.link = link;
  }

  public RssChannel description(String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }

  public RssChannel language(String language) {
    
    this.language = language;
    return this;
  }

  /**
   * Get language
   * @return language
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguage(String language) {
    this.language = language;
  }

  public RssChannel copyright(String copyright) {
    
    this.copyright = copyright;
    return this;
  }

  /**
   * Get copyright
   * @return copyright
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COPYRIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCopyright() {
    return copyright;
  }


  @JsonProperty(JSON_PROPERTY_COPYRIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCopyright(String copyright) {
    this.copyright = copyright;
  }

  public RssChannel managingEditor(String managingEditor) {
    
    this.managingEditor = managingEditor;
    return this;
  }

  /**
   * Get managingEditor
   * @return managingEditor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGING_EDITOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManagingEditor() {
    return managingEditor;
  }


  @JsonProperty(JSON_PROPERTY_MANAGING_EDITOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManagingEditor(String managingEditor) {
    this.managingEditor = managingEditor;
  }

  public RssChannel webMaster(String webMaster) {
    
    this.webMaster = webMaster;
    return this;
  }

  /**
   * Get webMaster
   * @return webMaster
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEB_MASTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWebMaster() {
    return webMaster;
  }


  @JsonProperty(JSON_PROPERTY_WEB_MASTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebMaster(String webMaster) {
    this.webMaster = webMaster;
  }

  public RssChannel pubDate(String pubDate) {
    
    this.pubDate = pubDate;
    return this;
  }

  /**
   * Get pubDate
   * @return pubDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUB_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPubDate() {
    return pubDate;
  }


  @JsonProperty(JSON_PROPERTY_PUB_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPubDate(String pubDate) {
    this.pubDate = pubDate;
  }

  public RssChannel lastBuildDate(String lastBuildDate) {
    
    this.lastBuildDate = lastBuildDate;
    return this;
  }

  /**
   * Get lastBuildDate
   * @return lastBuildDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_BUILD_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastBuildDate() {
    return lastBuildDate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_BUILD_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastBuildDate(String lastBuildDate) {
    this.lastBuildDate = lastBuildDate;
  }

  public RssChannel category(Category category) {
    
    this.category = category;
    return this;
  }

  /**
   * Get category
   * @return category
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Category getCategory() {
    return category;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategory(Category category) {
    this.category = category;
  }

  public RssChannel generator(String generator) {
    
    this.generator = generator;
    return this;
  }

  /**
   * Get generator
   * @return generator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GENERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGenerator() {
    return generator;
  }


  @JsonProperty(JSON_PROPERTY_GENERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGenerator(String generator) {
    this.generator = generator;
  }

  public RssChannel docs(String docs) {
    
    this.docs = docs;
    return this;
  }

  /**
   * Get docs
   * @return docs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocs() {
    return docs;
  }


  @JsonProperty(JSON_PROPERTY_DOCS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocs(String docs) {
    this.docs = docs;
  }

  public RssChannel cloud(Cloud cloud) {
    
    this.cloud = cloud;
    return this;
  }

  /**
   * Get cloud
   * @return cloud
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLOUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Cloud getCloud() {
    return cloud;
  }


  @JsonProperty(JSON_PROPERTY_CLOUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCloud(Cloud cloud) {
    this.cloud = cloud;
  }

  public RssChannel ttl(Integer ttl) {
    
    this.ttl = ttl;
    return this;
  }

  /**
   * Get ttl
   * @return ttl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TTL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTtl() {
    return ttl;
  }


  @JsonProperty(JSON_PROPERTY_TTL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTtl(Integer ttl) {
    this.ttl = ttl;
  }

  public RssChannel image(Image image) {
    
    this.image = image;
    return this;
  }

  /**
   * Get image
   * @return image
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Image getImage() {
    return image;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImage(Image image) {
    this.image = image;
  }

  public RssChannel rating(String rating) {
    
    this.rating = rating;
    return this;
  }

  /**
   * Get rating
   * @return rating
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRating() {
    return rating;
  }


  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRating(String rating) {
    this.rating = rating;
  }

  public RssChannel textInput(TextInput textInput) {
    
    this.textInput = textInput;
    return this;
  }

  /**
   * Get textInput
   * @return textInput
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TextInput getTextInput() {
    return textInput;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextInput(TextInput textInput) {
    this.textInput = textInput;
  }

  public RssChannel skipHours(SkipHoursList skipHours) {
    
    this.skipHours = skipHours;
    return this;
  }

  /**
   * Get skipHours
   * @return skipHours
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SKIP_HOURS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SkipHoursList getSkipHours() {
    return skipHours;
  }


  @JsonProperty(JSON_PROPERTY_SKIP_HOURS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSkipHours(SkipHoursList skipHours) {
    this.skipHours = skipHours;
  }

  public RssChannel skipDays(SkipDaysList skipDays) {
    
    this.skipDays = skipDays;
    return this;
  }

  /**
   * Get skipDays
   * @return skipDays
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SKIP_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SkipDaysList getSkipDays() {
    return skipDays;
  }


  @JsonProperty(JSON_PROPERTY_SKIP_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSkipDays(SkipDaysList skipDays) {
    this.skipDays = skipDays;
  }

  public RssChannel item(List<RssItem> item) {
    
    this.item = item;
    return this;
  }

  public RssChannel addItemItem(RssItem itemItem) {
    if (this.item == null) {
      this.item = new ArrayList<>();
    }
    this.item.add(itemItem);
    return this;
  }

  /**
   * Get item
   * @return item
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<RssItem> getItem() {
    return item;
  }


  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItem(List<RssItem> item) {
    this.item = item;
  }

  public RssChannel otherAttributes(Map<String, String> otherAttributes) {
    
    this.otherAttributes = otherAttributes;
    return this;
  }

  public RssChannel putOtherAttributesItem(String key, String otherAttributesItem) {
    if (this.otherAttributes == null) {
      this.otherAttributes = new HashMap<>();
    }
    this.otherAttributes.put(key, otherAttributesItem);
    return this;
  }

  /**
   * Get otherAttributes
   * @return otherAttributes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTHER_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getOtherAttributes() {
    return otherAttributes;
  }


  @JsonProperty(JSON_PROPERTY_OTHER_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtherAttributes(Map<String, String> otherAttributes) {
    this.otherAttributes = otherAttributes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RssChannel rssChannel = (RssChannel) o;
    return Objects.equals(this.title, rssChannel.title) &&
        Objects.equals(this.link, rssChannel.link) &&
        Objects.equals(this.description, rssChannel.description) &&
        Objects.equals(this.language, rssChannel.language) &&
        Objects.equals(this.copyright, rssChannel.copyright) &&
        Objects.equals(this.managingEditor, rssChannel.managingEditor) &&
        Objects.equals(this.webMaster, rssChannel.webMaster) &&
        Objects.equals(this.pubDate, rssChannel.pubDate) &&
        Objects.equals(this.lastBuildDate, rssChannel.lastBuildDate) &&
        Objects.equals(this.category, rssChannel.category) &&
        Objects.equals(this.generator, rssChannel.generator) &&
        Objects.equals(this.docs, rssChannel.docs) &&
        Objects.equals(this.cloud, rssChannel.cloud) &&
        Objects.equals(this.ttl, rssChannel.ttl) &&
        Objects.equals(this.image, rssChannel.image) &&
        Objects.equals(this.rating, rssChannel.rating) &&
        Objects.equals(this.textInput, rssChannel.textInput) &&
        Objects.equals(this.skipHours, rssChannel.skipHours) &&
        Objects.equals(this.skipDays, rssChannel.skipDays) &&
        Objects.equals(this.item, rssChannel.item) &&
        Objects.equals(this.otherAttributes, rssChannel.otherAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, link, description, language, copyright, managingEditor, webMaster, pubDate, lastBuildDate, category, generator, docs, cloud, ttl, image, rating, textInput, skipHours, skipDays, item, otherAttributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RssChannel {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    copyright: ").append(toIndentedString(copyright)).append("\n");
    sb.append("    managingEditor: ").append(toIndentedString(managingEditor)).append("\n");
    sb.append("    webMaster: ").append(toIndentedString(webMaster)).append("\n");
    sb.append("    pubDate: ").append(toIndentedString(pubDate)).append("\n");
    sb.append("    lastBuildDate: ").append(toIndentedString(lastBuildDate)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    generator: ").append(toIndentedString(generator)).append("\n");
    sb.append("    docs: ").append(toIndentedString(docs)).append("\n");
    sb.append("    cloud: ").append(toIndentedString(cloud)).append("\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    textInput: ").append(toIndentedString(textInput)).append("\n");
    sb.append("    skipHours: ").append(toIndentedString(skipHours)).append("\n");
    sb.append("    skipDays: ").append(toIndentedString(skipDays)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    otherAttributes: ").append(toIndentedString(otherAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

