/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.DocumentationType;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ValueSchemeType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Attribute
 */
class AttributeTest {
    private final Attribute model = new Attribute();

    /**
     * Model tests for Attribute
     */
    @Test
    void testAttribute() {
        // TODO: test Attribute
    }

    /**
     * Test the property 'documentation'
     */
    @Test
    void documentationTest() {
        // TODO: test documentation
    }

    /**
     * Test the property 'attributeValueScheme'
     */
    @Test
    void attributeValueSchemeTest() {
        // TODO: test attributeValueScheme
    }

    /**
     * Test the property 'autoValue'
     */
    @Test
    void autoValueTest() {
        // TODO: test autoValue
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'conceptLink'
     */
    @Test
    void conceptLinkTest() {
        // TODO: test conceptLink
    }

    /**
     * Test the property 'valueScheme'
     */
    @Test
    void valueSchemeTest() {
        // TODO: test valueScheme
    }

    /**
     * Test the property 'required'
     */
    @Test
    void requiredTest() {
        // TODO: test required
    }

    /**
     * Test the property 'otherAttributes'
     */
    @Test
    void otherAttributesTest() {
        // TODO: test otherAttributes
    }

}
