/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BaseDescription
 */
class BaseDescriptionTest {
    private final BaseDescription model = new BaseDescription();

    /**
     * Model tests for BaseDescription
     */
    @Test
    void testBaseDescription() {
        // TODO: test BaseDescription
    }

    /**
     * Test the property 'dbId'
     */
    @Test
    void dbIdTest() {
        // TODO: test dbId
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'registrationDate'
     */
    @Test
    void registrationDateTest() {
        // TODO: test registrationDate
    }

    /**
     * Test the property 'creatorName'
     */
    @Test
    void creatorNameTest() {
        // TODO: test creatorName
    }

    /**
     * Test the property 'dbUserId'
     */
    @Test
    void dbUserIdTest() {
        // TODO: test dbUserId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'href'
     */
    @Test
    void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'groupName'
     */
    @Test
    void groupNameTest() {
        // TODO: test groupName
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'derivedfrom'
     */
    @Test
    void derivedfromTest() {
        // TODO: test derivedfrom
    }

    /**
     * Test the property 'successor'
     */
    @Test
    void successorTest() {
        // TODO: test successor
    }

    /**
     * Test the property 'commentsCount'
     */
    @Test
    void commentsCountTest() {
        // TODO: test commentsCount
    }

    /**
     * Test the property 'content'
     */
    @Test
    void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'recommended'
     */
    @Test
    void recommendedTest() {
        // TODO: test recommended
    }

    /**
     * Test the property '_public'
     */
    @Test
    void _publicTest() {
        // TODO: test _public
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'showInEditor'
     */
    @Test
    void showInEditorTest() {
        // TODO: test showInEditor
    }

    /**
     * Test the property 'profile'
     */
    @Test
    void profileTest() {
        // TODO: test profile
    }

}
