/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Cloud
 */
class CloudTest {
    private final Cloud model = new Cloud();

    /**
     * Model tests for Cloud
     */
    @Test
    void testCloud() {
        // TODO: test Cloud
    }

    /**
     * Test the property 'domain'
     */
    @Test
    void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'port'
     */
    @Test
    void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'path'
     */
    @Test
    void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'registerProcedure'
     */
    @Test
    void registerProcedureTest() {
        // TODO: test registerProcedure
    }

    /**
     * Test the property 'protocol'
     */
    @Test
    void protocolTest() {
        // TODO: test protocol
    }

}
