/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Comment
 */
class CommentTest {
    private final Comment model = new Comment();

    /**
     * Model tests for Comment
     */
    @Test
    void testComment() {
        // TODO: test Comment
    }

    /**
     * Test the property 'commentDate'
     */
    @Test
    void commentDateTest() {
        // TODO: test commentDate
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'userName'
     */
    @Test
    void userNameTest() {
        // TODO: test userName
    }

    /**
     * Test the property 'canDelete'
     */
    @Test
    void canDeleteTest() {
        // TODO: test canDelete
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'comment'
     */
    @Test
    void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'componentRef'
     */
    @Test
    void componentRefTest() {
        // TODO: test componentRef
    }

}
