/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.AttributeListType;
import eu.clarin.cmdi.componentregistry.openapi.client.model.DocumentationType;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ElementType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ComponentType
 */
class ComponentTypeTest {
    private final ComponentType model = new ComponentType();

    /**
     * Model tests for ComponentType
     */
    @Test
    void testComponentType() {
        // TODO: test ComponentType
    }

    /**
     * Test the property 'documentation'
     */
    @Test
    void documentationTest() {
        // TODO: test documentation
    }

    /**
     * Test the property 'attributeList'
     */
    @Test
    void attributeListTest() {
        // TODO: test attributeList
    }

    /**
     * Test the property 'element'
     */
    @Test
    void elementTest() {
        // TODO: test element
    }

    /**
     * Test the property 'component'
     */
    @Test
    void componentTest() {
        // TODO: test component
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'componentRef'
     */
    @Test
    void componentRefTest() {
        // TODO: test componentRef
    }

    /**
     * Test the property 'conceptLink'
     */
    @Test
    void conceptLinkTest() {
        // TODO: test conceptLink
    }

    /**
     * Test the property 'cardinalityMin'
     */
    @Test
    void cardinalityMinTest() {
        // TODO: test cardinalityMin
    }

    /**
     * Test the property 'cardinalityMax'
     */
    @Test
    void cardinalityMaxTest() {
        // TODO: test cardinalityMax
    }

    /**
     * Test the property 'base'
     */
    @Test
    void baseTest() {
        // TODO: test base
    }

    /**
     * Test the property 'otherAttributes'
     */
    @Test
    void otherAttributesTest() {
        // TODO: test otherAttributes
    }

}
