/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ItemType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EnumerationType
 */
class EnumerationTypeTest {
    private final EnumerationType model = new EnumerationType();

    /**
     * Model tests for EnumerationType
     */
    @Test
    void testEnumerationType() {
        // TODO: test EnumerationType
    }

    /**
     * Test the property 'appinfo'
     */
    @Test
    void appinfoTest() {
        // TODO: test appinfo
    }

    /**
     * Test the property 'item'
     */
    @Test
    void itemTest() {
        // TODO: test item
    }

}
