/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ItemRights
 */
class ItemRightsTest {
    private final ItemRights model = new ItemRights();

    /**
     * Model tests for ItemRights
     */
    @Test
    void testItemRights() {
        // TODO: test ItemRights
    }

    /**
     * Test the property 'itemId'
     */
    @Test
    void itemIdTest() {
        // TODO: test itemId
    }

    /**
     * Test the property 'user'
     */
    @Test
    void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'canRead'
     */
    @Test
    void canReadTest() {
        // TODO: test canRead
    }

    /**
     * Test the property 'canWrite'
     */
    @Test
    void canWriteTest() {
        // TODO: test canWrite
    }

}
