/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ItemType
 */
class ItemTypeTest {
    private final ItemType model = new ItemType();

    /**
     * Model tests for ItemType
     */
    @Test
    void testItemType() {
        // TODO: test ItemType
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'conceptLink'
     */
    @Test
    void conceptLinkTest() {
        // TODO: test conceptLink
    }

    /**
     * Test the property 'appInfo'
     */
    @Test
    void appInfoTest() {
        // TODO: test appInfo
    }

    /**
     * Test the property 'otherAttributes'
     */
    @Test
    void otherAttributesTest() {
        // TODO: test otherAttributes
    }

}
