/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ProfileDescription;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProfileDescriptionsObject
 */
class ProfileDescriptionsObjectTest {
    private final ProfileDescriptionsObject model = new ProfileDescriptionsObject();

    /**
     * Model tests for ProfileDescriptionsObject
     */
    @Test
    void testProfileDescriptionsObject() {
        // TODO: test ProfileDescriptionsObject
    }

    /**
     * Test the property 'profileDescriptions'
     */
    @Test
    void profileDescriptionsTest() {
        // TODO: test profileDescriptions
    }

}
