/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.Category;
import eu.clarin.cmdi.componentregistry.openapi.client.model.Enclosure;
import eu.clarin.cmdi.componentregistry.openapi.client.model.Guid;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RssItem
 */
class RssItemTest {
    private final RssItem model = new RssItem();

    /**
     * Model tests for RssItem
     */
    @Test
    void testRssItem() {
        // TODO: test RssItem
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'link'
     */
    @Test
    void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'category'
     */
    @Test
    void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'comments'
     */
    @Test
    void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'enclosure'
     */
    @Test
    void enclosureTest() {
        // TODO: test enclosure
    }

    /**
     * Test the property 'guid'
     */
    @Test
    void guidTest() {
        // TODO: test guid
    }

    /**
     * Test the property 'pubDate'
     */
    @Test
    void pubDateTest() {
        // TODO: test pubDate
    }

    /**
     * Test the property 'any'
     */
    @Test
    void anyTest() {
        // TODO: test any
    }

    /**
     * Test the property 'otherAttributes'
     */
    @Test
    void otherAttributesTest() {
        // TODO: test otherAttributes
    }

}
