/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.VocabularyType;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ValueSchemeType
 */
class ValueSchemeTypeTest {
    private final ValueSchemeType model = new ValueSchemeType();

    /**
     * Model tests for ValueSchemeType
     */
    @Test
    void testValueSchemeType() {
        // TODO: test ValueSchemeType
    }

    /**
     * Test the property 'pattern'
     */
    @Test
    void patternTest() {
        // TODO: test pattern
    }

    /**
     * Test the property 'vocabulary'
     */
    @Test
    void vocabularyTest() {
        // TODO: test vocabulary
    }

}
