/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.componentregistry.openapi.client.model.EnumerationType;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VocabularyType
 */
class VocabularyTypeTest {
    private final VocabularyType model = new VocabularyType();

    /**
     * Model tests for VocabularyType
     */
    @Test
    void testVocabularyType() {
        // TODO: test VocabularyType
    }

    /**
     * Test the property 'enumeration'
     */
    @Test
    void enumerationTest() {
        // TODO: test enumeration
    }

    /**
     * Test the property 'uri'
     */
    @Test
    void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'valueProperty'
     */
    @Test
    void valuePropertyTest() {
        // TODO: test valueProperty
    }

    /**
     * Test the property 'valueLanguage'
     */
    @Test
    void valueLanguageTest() {
        // TODO: test valueLanguage
    }

}
