# Copyright (C) 2024 CLARIN ERIC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
editor.page.title=CMDI Component editor
editor.form.item.name=Name
editor.form.item.description=Description

editor.form.field.name=Name
editor.form.field.conceptLink=Concept link
editor.form.field.documentation=Documentation
editor.form.field.cardinalityMin=Min occurrences
editor.form.field.cardinalityMax=Max occurrences
editor.form.field.multilingual=Multilingual?
editor.form.field.otherAttributes=Other properties

editor.form.valueScheme.type.BOOLEAN=Boolean
editor.form.valueScheme.type.DECIMAL=Decimal
editor.form.valueScheme.type.FLOAT=Float
editor.form.valueScheme.type.INT=Integer
editor.form.valueScheme.type.STRING=String
editor.form.valueScheme.type.ANY_URI=anyURI (URL or URI)
editor.form.valueScheme.type.DATE=Date
editor.form.valueScheme.type.G_DAY=gDay (Day part of date)
editor.form.valueScheme.type.G_MONTH=gMonth (Month part of date)
editor.form.valueScheme.type.G_YEAR=gYear (Year part of date)
editor.form.valueScheme.type.TIME=Time
editor.form.valueScheme.type.DATE_TIME=dateTime (Date and time)