/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for AuthenticationApi
 */
@Ignore
public class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    
    /**
     * Information on the current authentication state. Pass &#39;redirect&#39; query parameter to make this method redirect to the URI specified as its value.
     *
     * 
     */
    @Test
    public void getAuthenticationInformationTest()  {
        String redirect = null;
        api.getAuthenticationInformation(redirect);

        // TODO: test validations
    }
    
    /**
     * Triggers the service to require the client to authenticate by means of the configured authentication mechanism. Notice that this might require user interaction!
     *
     * 
     */
    @Test
    public void triggerAuthenticationRequestTest()  {
        api.triggerAuthenticationRequest();

        // TODO: test validations
    }
    
}