/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.api;

import eu.clarin.cmdi.componentregistry.openapi.client.model.BaseDescription;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ComponentSpec;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ComponentRegistryControllerApi
 */
@Ignore
public class ComponentRegistryControllerApiTest {

    private final ComponentRegistryControllerApi api = new ComponentRegistryControllerApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void getItemTest()  {
        String componentId = null;
        BaseDescription response = api.getItem(componentId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getItemSpecTest()  {
        String componentId = null;
        ComponentSpec response = api.getItemSpec(componentId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getItemsTest()  {
        String sortBy = null;
        String sortDirection = null;
        List<BaseDescription> response = api.getItems(sortBy, sortDirection);

        // TODO: test validations
    }
    
}