/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.api;

import eu.clarin.cmdi.componentregistry.openapi.client.model.BaseDescription;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void getExternalGrammarTest()  {
        String path = null;
        api.getExternalGrammar(path);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getTestItemTest()  {
        BaseDescription response = api.getTestItem();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getWadlTest()  {
        api.getWadl();

        // TODO: test validations
    }
    
}