/*
 * Component Registry API
 * Components and profiles registry for the Component Metadata Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cmdi@clarin.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.api;

import eu.clarin.cmdi.componentregistry.openapi.client.model.BaseDescription;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ComponentSpec;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ItemsControllerApi
 */
@Ignore
public class ItemsControllerApiTest {

    private final ItemsControllerApi api = new ItemsControllerApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void getItemTest()  {
        String componentId = null;
        BaseDescription response = api.getItem(componentId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getItemSpecTest()  {
        String componentId = null;
        ComponentSpec response = api.getItemSpec(componentId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getItemsTest()  {
        String type = null;
        List<String> status = null;
        String sortBy = null;
        String sortDirection = null;
        List<BaseDescription> response = api.getItems(type, status, sortBy, sortDirection);

        // TODO: test validations
    }
    
}