/*
 * CLARIN Component Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.componentregistry.openapi.client.api;

import eu.clarin.cmdi.componentregistry.openapi.client.model.BaseDescription;
import eu.clarin.cmdi.componentregistry.openapi.client.model.Group;
import eu.clarin.cmdi.componentregistry.openapi.client.model.ItemRights;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ItemsApi
 */
@Ignore
public class ItemsApiTest {

    private final ItemsApi api = new ItemsApi();

    
    /**
     * The description (metadata) of a single component or profile item
     *
     * 
     */
    @Test
    public void getBaseDescriptionTest()  {
        String itemId = null;
        BaseDescription response = api.getBaseDescription(itemId);

        // TODO: test validations
    }
    
    /**
     * Returns a listing of groups to which an item belongs
     *
     * 
     */
    @Test
    public void getGroupsTheItemIsAMemberOfTest()  {
        String itemId = null;
        List<Group> response = api.getGroupsTheItemIsAMemberOf(itemId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getItemLockTest()  {
        String itemId = null;
        api.getItemLock(itemId);

        // TODO: test validations
    }
    
    /**
     * Returns information about the rights to an item for the current user
     *
     * 
     */
    @Test
    public void getItemRightsTest()  {
        String itemId = null;
        ItemRights response = api.getItemRights(itemId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void putItemLockTest()  {
        String itemId = null;
        api.putItemLock(itemId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void removeItemLockTest()  {
        String itemId = null;
        api.removeItemLock(itemId);

        // TODO: test validations
    }
    
    /**
     * Transfers an item to the specified group (either from the private space or another group)
     *
     * 
     */
    @Test
    public void transferItemOwnershipToGroupTest()  {
        String itemId = null;
        Long groupId = null;
        api.transferItemOwnershipToGroup(itemId, groupId);

        // TODO: test validations
    }
    
}